#!/usr/bin/env python3
"""
detection/entropy_detector.py

Offline entropy-based DDoS detector used to calibrate ENTROPY_THRESH before
it is hard-coded into controller/ddos_controller.py.

Dataset handling (proposal Step 4: "figure out the right threshold values
for entropy by testing them on a subset of the CICDDoS2019 dataset"):
  --input can point at either
    (a) a real CICDDoS2019 CSV exported from the CIC-provided dataset
        (columns detected automatically: " Source IP" / "Label" or similar
        CICFlowMeter naming), or
    (b) the synthetic calibration_flows.csv fallback generated by
        traffic/traffic_gen.py or the Phase 2 generator script, used only
        when the real dataset is not available.
  The script prints clearly which one it loaded -- this must be stated
  honestly in the report; do not claim CICDDoS2019 calibration if the
  synthetic fallback was actually used.

Modes:
  --sweep      Threshold sweep (0.5 - 4.5 bits), reports acc/f1/fpr/fnr per
               threshold, picks the F1-optimal value, and saves a plot
               (results/plots/fig3_threshold_sweep.png by default).
  (default)    Compute entropy for a single CSV and report alarm/no-alarm.

Run:
    python3 detection/entropy_detector.py --input data/calibration_flows.csv --sweep
    python3 detection/entropy_detector.py --input data/CICDDoS2019_subset.csv --sweep
    python3 detection/entropy_detector.py --input data/calibration_flows.csv --sweep --window-size 50 --chosen-threshold 2.5 --output results/plots/fig3_threshold_sweep.png
"""
import argparse
import collections
import csv
import math
import os

import matplotlib.pyplot as plt

# Column names CICFlowMeter / CICDDoS2019 exports commonly use for the
# source IP and label fields (varies slightly by export tool/version).
CIC_SRC_IP_CANDIDATES = ["Source IP", " Source IP", "src_ip", "Src IP"]
CIC_LABEL_CANDIDATES = ["Label", " Label", "label"]
CIC_BENIGN_TOKENS = {"benign", "0", "normal"}


def shannon_entropy(counter):
    total = sum(counter.values())
    if not total:
        return 0.0
    return -sum((c / total) * math.log2(c / total) for c in counter.values() if c)


def _detect_column(fieldnames, candidates):
    for c in candidates:
        if c in fieldnames:
            return c
    return None


def load_rows(path):
    """Loads either the synthetic calibration_flows.csv schema (src_ip,
    label already 0/1) or a real CICDDoS2019 export, normalising both to
    the same internal schema: {"src_ip": ..., "label": "0"/"1"}."""
    with open(path) as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames or []
        rows_raw = list(reader)

    if "src_ip" in fieldnames and "label" in fieldnames:
        print(f"Loaded {len(rows_raw)} flows from {path} (synthetic calibration schema)")
        return rows_raw, "synthetic"

    src_col = _detect_column(fieldnames, CIC_SRC_IP_CANDIDATES)
    label_col = _detect_column(fieldnames, CIC_LABEL_CANDIDATES)
    if src_col and label_col:
        normalised = []
        for r in rows_raw:
            label_raw = str(r.get(label_col, "")).strip().lower()
            label = "0" if label_raw in CIC_BENIGN_TOKENS else "1"
            normalised.append({"src_ip": r.get(src_col, "unknown"), "label": label})
        print(f"Loaded {len(normalised)} flows from {path} (real CICDDoS2019 export, "
              f"src column='{src_col}', label column='{label_col}')")
        return normalised, "cicddos2019"

    raise ValueError(
        f"Could not find recognisable src-IP/label columns in {path}. "
        f"Found columns: {fieldnames}"
    )


def make_windows(rows, window_size=50):
    """Splits flow-level records into fixed-size windows, mirroring how the
    live controller polls flow stats every POLL_INTERVAL and computes
    entropy over whichever flows are active in THAT window."""
    windows = []
    for i in range(0, len(rows), window_size):
        chunk = rows[i:i + window_size]
        if not chunk:
            continue
        attack_frac = sum(int(r["label"]) for r in chunk) / len(chunk)
        window_label = 1 if attack_frac > 0.5 else 0
        windows.append((chunk, window_label))
    return windows


def confusion_at_threshold(rows, thresh, window_size=50):
    windows = make_windows(rows, window_size)
    TP = FP = TN = FN = 0
    for chunk, label in windows:
        src_ctr = collections.Counter(r["src_ip"] for r in chunk)
        h = shannon_entropy(src_ctr)
        alarm = h < thresh
        if alarm and label:
            TP += 1
        elif alarm and not label:
            FP += 1
        elif not alarm and not label:
            TN += 1
        else:
            FN += 1
    return TP, FP, TN, FN


def metrics(TP, FP, TN, FN):
    total = TP + FP + TN + FN
    acc = (TP + TN) / total if total else 0
    prec = TP / (TP + FP) if (TP + FP) else 0
    rec = TP / (TP + FN) if (TP + FN) else 0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0
    fpr = FP / (FP + TN) if (FP + TN) else 0
    fnr = FN / (FN + TP) if (FN + TP) else 0
    return acc, prec, rec, f1, fpr, fnr


def plot_sweep(thresholds, accs, f1s, fprs, fnrs, best_thresh, chosen_thresh, output_path):
    """Renders the accuracy/F1/FPR/FNR-vs-threshold sweep and saves it as a
    PNG, in the same style as the report's Figure 3."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    fig, ax = plt.subplots(figsize=(8.5, 4.5))

    ax.plot(thresholds, accs, marker="o", color="#1F3FBF", label="Accuracy (%)")
    ax.plot(thresholds, f1s, marker="s", color="#2E8B22", label="F1 Score (%)")
    ax.plot(thresholds, fprs, marker="^", color="#D62222", label="FPR (%)")
    ax.plot(thresholds, fnrs, marker="D", color="#B23AC9", label="FNR (%)")

    ax.axvline(best_thresh, color="#E2A73A", linestyle="--",
               label=f"Best F1 threshold = {best_thresh} bits")
    if chosen_thresh is not None:
        ax.axvline(chosen_thresh, color="gray", linestyle=":",
                   label=f"Chosen operating threshold = {chosen_thresh}")

    ax.set_xlabel("Entropy Threshold (bits)")
    ax.set_ylabel("Score (%)")
    ax.set_title("Detection Performance vs Entropy Threshold (window-based sweep)",
                 fontweight="bold")
    ax.set_ylim(-5, 105)
    ax.grid(True, alpha=0.3, linestyle="--")
    ax.legend(loc="center right", fontsize=8)

    fig.tight_layout()
    plt.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close()
    print(f"Saved: {output_path}")


def plot_confusion_matrix(TP, FP, TN, FN, thresh, output_path):
    """Renders a 2x2 confusion matrix (Attack/Benign x Predicted Attack/
    Predicted Benign) at a single fixed threshold and saves it as a PNG."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # rows = actual class, cols = predicted class
    matrix = [[TP, FN],
              [FP, TN]]
    labels = ["Attack", "Benign"]

    fig, ax = plt.subplots(figsize=(5, 4.5))
    im = ax.imshow(matrix, cmap="Blues")

    ax.set_xticks([0, 1])
    ax.set_yticks([0, 1])
    ax.set_xticklabels([f"Predicted\n{l}" for l in labels])
    ax.set_yticklabels([f"Actual\n{l}" for l in labels])

    max_val = max(TP, FP, TN, FN) or 1
    for i in range(2):
        for j in range(2):
            val = matrix[i][j]
            color = "white" if val > max_val * 0.5 else "black"
            ax.text(j, i, str(val), ha="center", va="center",
                    color=color, fontsize=16, fontweight="bold")

    ax.set_title(f"Confusion Matrix (threshold = {thresh} bits)", fontweight="bold")
    fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    fig.tight_layout()
    plt.savefig(output_path, dpi=180, bbox_inches="tight")
    plt.close()
    print(f"Saved: {output_path}")


def sweep(rows, window_size=50, chosen_thresh=2.5, output_path="results/plots/fig3_threshold_sweep.png",
          confusion_output_path="results/plots/fig4_confusion_matrix.png"):
    thresholds = [round(t * 0.25, 2) for t in range(2, 19)]  # 0.5 .. 4.5

    accs, f1s, fprs, fnrs = [], [], [], []
    best = None

    for thresh in thresholds:
        TP, FP, TN, FN = confusion_at_threshold(rows, thresh, window_size=window_size)
        acc, prec, rec, f1, fpr, fnr = metrics(TP, FP, TN, FN)

        print(f"thresh={thresh:5.2f}  acc={acc*100:6.2f}%  f1={f1*100:6.2f}%  "
              f"fpr={fpr*100:6.2f}%  fnr={fnr*100:6.2f}%  "
              f"(TP={TP} FP={FP} TN={TN} FN={FN})")

        accs.append(acc * 100)
        f1s.append(f1 * 100)
        fprs.append(fpr * 100)
        fnrs.append(fnr * 100)

        if best is None or f1 > best[1]:
            best = (thresh, f1, fpr, fnr)

    print()
    print(f"Best threshold: {best[0]} bits | F1={best[1]*100:.1f}% | "
          f"FPR={best[2]*100:.1f}% | FNR={best[3]*100:.1f}%")

    plot_sweep(thresholds, accs, f1s, fprs, fnrs, best[0], chosen_thresh, output_path)

    # Confusion matrix at the chosen OPERATING threshold (e.g. 2.5, the one
    # actually hard-coded into the live controller) -- not the best-F1
    # threshold, since the report should show performance at the threshold
    # that's actually deployed.
    TP, FP, TN, FN = confusion_at_threshold(rows, chosen_thresh, window_size=window_size)
    print(f"\nConfusion matrix @ chosen threshold ({chosen_thresh} bits): "
          f"TP={TP} FP={FP} TN={TN} FN={FN}")
    plot_confusion_matrix(TP, FP, TN, FN, chosen_thresh, confusion_output_path)

    return best[0]


def main():
    parser = argparse.ArgumentParser(description="Entropy-based DDoS detector (offline)")
    parser.add_argument("--input", required=True, help="calibration CSV path (synthetic or real CICDDoS2019)")
    parser.add_argument("--sweep", action="store_true", help="run threshold sweep")
    parser.add_argument("--threshold", type=float, default=2.5, help="single-shot threshold")
    parser.add_argument("--window-size", type=int, default=50,
                         help="flows per window for the sweep (default: 50)")
    parser.add_argument("--chosen-threshold", type=float, default=2.5,
                         help="operating threshold to mark on the sweep plot (default: 2.5)")
    parser.add_argument("--output", default="results/plots/fig3_threshold_sweep.png",
                         help="where to save the sweep plot PNG")
    parser.add_argument("--confusion-output", default="results/plots/fig4_confusion_matrix.png",
                         help="where to save the confusion matrix PNG")
    args = parser.parse_args()

    rows, source = load_rows(args.input)
    if source == "synthetic":
        print("NOTE: this run used the SYNTHETIC fallback dataset, not the real "
              "CICDDoS2019 dataset. State this accurately in the report.")

    if args.sweep:
        sweep(rows, window_size=args.window_size,
              chosen_thresh=args.chosen_threshold, output_path=args.output,
              confusion_output_path=args.confusion_output)
    else:
        src_ctr = collections.Counter(r["src_ip"] for r in rows)
        h = shannon_entropy(src_ctr)
        alarm = h < args.threshold
        print(f"Entropy H(src_ip) = {h:.4f} bits")
        print("ALERT: DDoS suspected" if alarm else "OK: traffic looks benign")


if __name__ == "__main__":
    main()
